# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# Entendo o que faz os comandos:
# Quando ocorrer um push na branch master esse gatilho será disparado e o build será executado.
# O mesmo caso quando ocorrer um pull request na branch master.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # Máquina que irá executar os testes
    runs-on: ubuntu-latest
    
    #Configurar versão do node
    strategy:
      matrix:
        node-version: [12.x] # Pode ser configura uma matriz com várias versões do nome.

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Configuração que irá instalar o node
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2 # As actions seriam como fosse as dependências do NPM instaladas no projeto
        with:
          node-version: ${{ matrix.node-version }} # Aqui foi passado as informações da linha 30 e 31, em forma de uma variável.
                    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Essa action irá baixar o codigo para a máquina remota que irá executar o build
      - uses: actions/checkout@v2

      # Instalando as dependências do arquivo package.json do nosso projeto, na máquina remota
      - run: npm install
      
      # Não será necessário configurar o script 'npm run report:clean', pois a cada execução na máquina remota, a mesma é zerada.  
            
      - run: npm run cy:run
      - run: npm run report:merge
      - run: npm run report:mocha
        
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.9 # Action de terceiros
        with:
          GITHUB_TOKEN: $ {{ secrets.GITHUB_TOKEN }} # Essa variável será capturada do nosso github, pois estamos usando uma action de terceiros. 
          BRANCH: gh-pages
          FOLDER: mochawesome-report # Aqui é a pasta que irá conter o arquivo .html para ser exibido no GH Pages.
